---
services:
  db:
    image: "postgres:14-alpine"
    env_file:
      - "development.env"
      - "creds.env"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      # - "./nautobot.sql:/tmp/nautobot.sql"
      - "postgres_data:/var/lib/postgresql/data"
    healthcheck:
      test: "pg_isready --username=$$POSTGRES_USER --dbname=$$POSTGRES_DB"
      interval: "10s"
      timeout: "5s"
      retries: 10
  redis:
    image: "redis:6-alpine"
    command:
      - "sh"
      - "-c"  # this is to evaluate the $NAUTOBOT_REDIS_PASSWORD from the env
      - "redis-server --appendonly yes --requirepass $$NAUTOBOT_REDIS_PASSWORD"
    env_file:
      - "development.env"
      - "creds.env"
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  postgres_data: {}
