---
dev_addr: "127.0.0.1:8001"
edit_uri: "edit/main/nautobot-app-consumables/docs"
site_dir: "nautobot_consumables/static/nautobot_consumables/docs"
site_name: "Nautobot Consumables Documentation"
site_url: "https://github.com/NVIDIA/nautobot-app-consumables"
repo_url: "https://github.com/NVIDIA/nautobot-app-consumables"
theme:
  name: "material"
  navigation_depth: 4
  hljs_languages:
    - "django"
    - "yaml"
  features:
    - "content.code.copy"
    - "navigation.tabs"
    - "navigation.tabs.sticky"
    - "navigation.tracking"
    - "search.highlight"
    - "search.share"
    - "search.suggest"
  favicon: "assets/favicon.ico"
  logo: "assets/nvidia-logo-vert-rgb-wht-for-screen.png"
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to system preference
extra_css:
  - "extra.css"

markdown_extensions:
  - "admonition"
  - "attr_list"
  - "def_list"
  - toc:
      permalink: true
  - "footnotes"
  - "md_in_html"
  - "pymdownx.details"
  - "pymdownx.highlight":
      anchor_linenums: true
  - "pymdownx.inlinehilite"
  - "pymdownx.snippets"
  - "pymdownx.superfences"
  - "sane_lists"

plugins:
  - "search"
  - "include-markdown"
  - "mkdocs-version-annotations"
  - "mkdocstrings":
      default_handler: "python"
      handlers:
        python:
          paths: ["."]
          options:
            show_root_heading: true

watch:
  - "README.md"

nav:
  - Introduction: "index.md"
  - User Guide:
      - Overview: "user/index.md"
      - Model Details:
          - Consumable Type: "models/consumabletype.md"
          - Consumable: "models/consumable.md"
          - Consumable Pool: "models/consumablepool.md"
          - Checked Out Consumable: "models/checkedoutconsumable.md"
  - Administrator Guide:
      - Install: "admin/install.md"
      - Upgrade: "admin/upgrade.md"
      - Uninstall: "admin/uninstall.md"
      - Compatibility Matrix: "admin/compatibility_matrix.md"
      - Release Notes:
          - "admin/release_notes/index.md"
          - v1.0: "admin/release_notes/version_1.0.md"
  - Developer Guide:
      - Contributing to the App: "dev/contributing.md"
      - Development Environment: "dev/dev_env.md"
      - Code Reference:
          - "dev/code_reference/index.md"
          - Package: "dev/code_reference/package.md"
          - API: "dev/code_reference/api.md"
          - Models: "dev/code_reference/models.md"
